### ISSUE TITLE
view_slice in RadioMask

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/signal-id#31]
Make it easier to view changes in the mask with a convenience function for viewing planes. Manually calling ```plt.imshow```, etc... gets tiresome.

**Comment by keflavich** [comment]
@e-koch does this belong in spectral-cube, since masks are defined there?

**Comment by e-koch** [comment]
I think that could be handy to have in spectral-cube. ```RadioMask``` may still need its own quick view type function, since the mask operations are performed on arrays instead of the spectral-cube mask objects. I guess that brings up the question of whether we should be using spectral-cube masks by default. @keflavich any thoughts on that point? I only have a basic understanding of what the masks in spectral-cube are doing.

**Comment by keflavich** [comment]
SpectralCube's masks can be lazy: they can be created without being evaluated.   They have a `.include()` method that provides the actual array, which can always be accessed as a subset with the `view` keyword.  If you're operating on `SpectralCube`'s, it's probably a good idea to at least generate the `RadioMask`s from `SpectralCube.mask`s, but maybe even worth inheriting from them.

**Comment by e-koch** [comment]
```RadioMask``` should probably be rewritten to inherit from ```MaskBase``` then. The quick view for slices could then be added onto ```MaskBase``` - @keflavich was this where you were thinking that functionality could live?

**Comment by keflavich** [comment]
Yes, I think that's a good idea.  Should the quick look be similar to, or perhaps also inherit, [that from Projections](https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/lower_dimensional_structures.py#L93)?

**Comment by e-koch** [comment]
```quicklook``` addressed [here](https://github.com/radio-astro-tools/spectral-cube/pull/228#event-381667254)

Anything about switching to use ```MaskBase``` can be moved to #33
